# Generated by Django 5.1.5 on 2025-01-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Característica', 'verbose_name_plural': 'Características'},
        ),
    ]
