# Generated by Django 5.1.5 on 2025-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_features_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='resumo',
            field=models.TextField(default='preenche', max_length=200, verbose_name='Resumo'),
            preserve_default=False,
        ),
    ]
