# Generated by Django 5.1.5 on 2025-02-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cargo_resumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='resumo',
        ),
    ]
